[package]
name = "easyraw"
version = "0.1.0"
authors = ["Brad Alfirevic <brad@genbyte.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
rawproc = { path = "../rawproc" }
image = { version = "0.23", default-features = false, features = ["jpeg"] }
threadpool = "1.8.1"